name: Build Milvus Connector
on: [push, workflow_dispatch]
jobs:
  build-jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build with Docker
        run: docker build -t milvus-builder .
      - name: Export JAR
        run: |
          docker create --name temp milvus-builder
          # Tìm và lấy file jar assembly
          docker cp temp:/workspace/target/scala-2.13/spark-connector-assembly-0.1.7-SNAPSHOT.jar ./connector.jar
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: milvus-jar-xịn
          path: ./connector.jar
